# Generated by Django 5.0.4 on 2024-11-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashtag_name', models.CharField(max_length=200)),
            ],
        ),
    ]
