# Generated by Django 5.0.4 on 2024-11-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hashtags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtags',
            options={'managed': False},
        ),
    ]
