# Generated by Django 5.0.4 on 2024-11-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hashtags_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hashtags',
            table='Hashtags',
        ),
    ]
