# Generated by Django 5.0.4 on 2024-11-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hashtags_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
